# Generated by Django 5.0.2 on 2025-05-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('ANONYMOUS', 'Anonymous'), ('GROUP', 'Group')], default='GROUP', max_length=10),
        ),
    ]
