# Generated by Django 5.0.2 on 2025-06-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_user_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferences',
        ),
    ]
