# Generated by Django 5.0.2 on 2025-06-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='preferences',
            field=models.JSONField(blank=True, help_text='Preferences for anonymous chat matching', null=True),
        ),
    ]
